---
- name: Install vscode
  homebrew_cask:
    name: visual-studio-code

- name: Get the list of installed VSCode extensions
  shell: "code --list-extensions | tr '[:upper:]' '[:lower:]'"
  register: installed_vscode_extensions
  changed_when: False

- name: Install VSCode extensions
  command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions | difference(installed_vscode_extensions.stdout_lines) }}"

- name: Install user settings file
  copy:
    src: settings.json
    dest: "~/Library/Application Support/Code/User/settings.json"
