---
- name: Install VirtualBox
  homebrew_cask:
    name: virtualbox

- name: Install Vagrant
  homebrew_cask:
    name: vagrant

- name: Install Vagrant manager
  homebrew_cask:
    name: vagrant-manager

