- name: Symlink git configuration
  include: roles/dotfiles/tasks/symlink.yml src=.gitconfig force=true

- name: Install git-so-fancy
  become: true
  get_url:
    url: "https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy"
    dest: "/usr/local/bin"
    mode: 0755

